import type { GetServerSideProps, NextPage } from 'next'
import { getSession, GetSessionParams } from 'next-auth/react'
import Head from 'next/head'
import Image from 'next/image'
import Header from '../components/Header'
import Login from '../components/Login'
import Sidebar from '../components/Sidebar'

interface Props {
  session: UserSession
}

interface UserSession {
  user: {
    email: string;
    image: string;
    name: string;
  }
}

const Home: NextPage<Props> = ({ session }) => {
  if (!session) { return <Login /> }
  
  console.log(session)

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main>
        <Sidebar />
      </main>
    </div>
  )
}

export default Home


export const getServerSideProps: any = async (context: GetSessionParams) => {
  const session = await getSession(context)
  
  return {
    props: {
      session
    }
  }

}